analyzer:
  errors:
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false


formatter:
  page_width: 120