name: beat_it
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.14
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_command: ^7.2.2
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  result_dart: ^2.0.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.3
  uuid: ^4.3.3
  very_good_analysis: ^7.0.0
  watch_it: ^1.6.2
  intl: ^0.18.0

dev_dependencies: 
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
