default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    if !ENV['CI']
      begin
        Dotenv.load('.env.local')
      rescue
        puts "No .env.local file found, continuing without it"
      end
    end
    
    setup_ci if ENV['CI']
    
    # Sync both development and appstore certificates
    match(type: "development", readonly: true)
    match(type: "appstore", readonly: true)
    
    # Update code signing settings
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      team_id: ENV["TEAM_ID"],
      targets: ["Runner"],
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AppStore com.scheiermannandre.beatIt",
      bundle_identifier: "com.scheiermannandre.beatIt"
    )
    
    # Build the app
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.scheiermannandre.beatIt" => "match AppStore com.scheiermannandre.beatIt"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"]
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      apple_id: "6740911066"
    )
  end
end