default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    if !ENV['CI']
      begin
        Dotenv.load('.env.local')
      rescue
        puts "No .env.local file found, continuing without it"
      end
    end
    
    setup_ci if ENV['CI']
    
    # Sync both development and appstore certificates
    match(type: "development", readonly: true)
    match(type: "appstore", readonly: true)
    
    # Build the app with specific export options
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.scheiermannandre.beatIt" => "match AppStore com.scheiermannandre.beatIt"
        }
      }
    )
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: false
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      apple_id: "6740911066"
    )
  end
end